language: c
compiler: gcc
before_install:
  - sudo apt-get install automake autoconf autotools-dev libtool
#  - sudo apt-get install libcfitsio-dev
script:
  - ./bootstrap;
    mkdir build;
    cd build;
    ../libtao/configure
#    make
