/*
 * dump-errors.c -
 *
 * Dump error messages of ActiveSilicon Phoenix frame grabber library.
 *
 *-----------------------------------------------------------------------------
 *
 * This file if part of TAO software (https://github.com/emmt/TAO) licensed
 * under the MIT license.
 *
 * Copyright (C) 2018, Éric Thiébaut.
 */

#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <phx_api.h>

int main(int argc, char** argv)
{
    char buffer[4096];
    char* str;
    long len;
    FILE* output = stdout;

    fputs("\
/*\n\
 * errors.c -\n\
 *\n\
 * Error messages of ActiveSilicon Phoenix frame grabber library.\n\
 *\n\
 * IMPORTANT: This file is automatically generated, do not edit.\n\
 *\n\
 *-----------------------------------------------------------------------------\n\
 *\n\
 * This file if part of TAO software (https://github.com/emmt/TAO) licensed\n\
 * under the MIT license.\n\
 *\n\
 * Copyright (C) 2018, Éric Thiébaut.\n\
 */\n\
\n\
#include \"phoenix.h\"\n\
\n\
const char*\n\
phx_status_description(phx_status_t status)\n\
{\n\
    switch(status) {\n", output);

#define PRT(id)                                                         \
    do {                                                                \
        str = buffer;                                                   \
        str[0] = '\0';                                                  \
        PHX_ErrCodeDecode(buffer, id);                                  \
        if (str[0] == '(') {                                            \
            len = strlen(str);                                          \
            if (str[len - 1] == ')') {                                  \
                str[len - 1] = '\0';                                    \
                ++str;                                                  \
            }                                                           \
        }                                                               \
        fprintf(output, "    case %s: return \"%s\";\n", #id, str);     \
    } while (false)

    /* Standard errors. */
    fputs("    case PHX_OK: return \"No errors\";\n", output);
    PRT(PHX_ERROR_BAD_HANDLE);
    PRT(PHX_ERROR_BAD_PARAM);
    PRT(PHX_ERROR_BAD_PARAM_VALUE);
    PRT(PHX_ERROR_READ_ONLY_PARAM);
    PRT(PHX_ERROR_OPEN_FAILED);
    PRT(PHX_ERROR_INCOMPATIBLE);
    PRT(PHX_ERROR_HANDSHAKE);
    PRT(PHX_ERROR_INTERNAL_ERROR);
    PRT(PHX_ERROR_OVERFLOW);
    PRT(PHX_ERROR_NOT_IMPLEMENTED);
    PRT(PHX_ERROR_HW_PROBLEM);
    PRT(PHX_ERROR_NOT_SUPPORTED);
    PRT(PHX_ERROR_OUT_OF_RANGE);
    PRT(PHX_ERROR_MALLOC_FAILED);
    PRT(PHX_ERROR_SYSTEM_CALL_FAILED);
    PRT(PHX_ERROR_FILE_OPEN_FAILED);
    PRT(PHX_ERROR_FILE_CLOSE_FAILED);
    PRT(PHX_ERROR_FILE_INVALID);
    PRT(PHX_ERROR_BAD_MEMBER);
    PRT(PHX_ERROR_HW_NOT_CONFIGURED);
    PRT(PHX_ERROR_INVALID_FLASH_PROPERTIES);
    PRT(PHX_ERROR_ACQUISITION_STARTED);
    PRT(PHX_ERROR_INVALID_POINTER);
    PRT(PHX_ERROR_LIB_INCOMPATIBLE);
    PRT(PHX_ERROR_SLAVE_MODE);

    /* Phoenix display library errors */
    PRT(PHX_ERROR_DISPLAY_CREATE_FAILED);
    PRT(PHX_ERROR_DISPLAY_DESTROY_FAILED);
    PRT(PHX_ERROR_DDRAW_INIT_FAILED);
    PRT(PHX_ERROR_DISPLAY_BUFF_CREATE_FAILED);
    PRT(PHX_ERROR_DISPLAY_BUFF_DESTROY_FAILED);
    PRT(PHX_ERROR_DDRAW_OPERATION_FAILED);

    /* Registry errors */
    PRT(PHX_ERROR_WIN32_REGISTRY_ERROR);
    PRT(PHX_ERROR_PROTOCOL_FAILURE);

    /* Warnings. */
    PRT(PHX_WARNING_TIMEOUT);
    PRT(PHX_WARNING_FLASH_RECONFIG);
    PRT(PHX_WARNING_ZBT_RECONFIG);
    PRT(PHX_WARNING_NOT_PHX_COM);
    PRT(PHX_WARNING_NO_PHX_BOARD_REGISTERED);
    PRT(PHX_WARNING_TIMEOUT_EXTENDED);

    fputs("\
    default: return \"Unknown error\";\n\
    }\n\
}\n", output);
    return 0;
}
